In [115]:
import pandas as pd
import numpy as np

In [116]:
df1 = pd.read_csv('dataset/city_day.csv')
df1.head()

City        Date  PM2.5  PM10     NO    NO2    NOx  NH3     CO    SO2  \
0  Ahmedabad  2015-01-01    NaN   NaN   0.92  18.22  17.15  NaN   0.92  27.64   
1  Ahmedabad  2015-01-02    NaN   NaN   0.97  15.69  16.46  NaN   0.97  24.55   
2  Ahmedabad  2015-01-03    NaN   NaN  17.40  19.30  29.70  NaN  17.40  29.07   
3  Ahmedabad  2015-01-04    NaN   NaN   1.70  18.48  17.97  NaN   1.70  18.59   
4  Ahmedabad  2015-01-05    NaN   NaN  22.10  21.42  37.76  NaN  22.10  39.33   

       O3  Benzene  Toluene  Xylene  AQI AQI_Bucket  
0  133.36     0.00     0.02    0.00  NaN        NaN  
1   34.06     3.68     5.50    3.77  NaN        NaN  
2   30.70     6.80    16.40    2.25  NaN        NaN  
3   36.08     4.43    10.14    1.00  NaN        NaN  
4   39.31     7.01    18.89    2.78  NaN        NaN

In [117]:
df1['City'].unique()


array(['Ahmedabad', 'Aizawl', 'Amaravati', 'Amritsar', 'Bengaluru',
       'Bhopal', 'Brajrajnagar', 'Chandigarh', 'Chennai', 'Coimbatore',
       'Delhi', 'Ernakulam', 'Gurugram', 'Guwahati', 'Hyderabad',
       'Jaipur', 'Jorapokhar', 'Kochi', 'Kolkata', 'Lucknow', 'Mumbai',
       'Patna', 'Shillong', 'Talcher', 'Thiruvananthapuram',
       'Visakhapatnam'], dtype=object)

In [118]:
df = df1[df1['City']=='Delhi']
df

City        Date   PM2.5    PM10     NO    NO2     NOx     NH3     CO  \
10229  Delhi  2015-01-01  313.22  607.98  69.16  36.39  110.59   33.85  15.20   
10230  Delhi  2015-01-02  186.18  269.55  62.09  32.87   88.14   31.83   9.54   
10231  Delhi  2015-01-03   87.18  131.90  25.73  30.31   47.95   69.55  10.61   
10232  Delhi  2015-01-04  151.84  241.84  25.01  36.91   48.62  130.36  11.54   
10233  Delhi  2015-01-05  146.60  219.13  14.01  34.92   38.25  122.88   9.20   
...      ...         ...     ...     ...    ...    ...     ...     ...    ...   
12233  Delhi  2020-06-27   39.80  155.94  10.88  21.46   22.47   31.43   0.87   
12234  Delhi  2020-06-28   59.52  308.65  12.67  21.60   23.86   29.27   0.94   
12235  Delhi  2020-06-29   44.86  184.12  10.50  21.57   21.94   27.97   0.88   
12236  Delhi  2020-06-30   39.80   91.98   5.99  17.96   15.44   28.48   0.84   
12237  Delhi  2020-07-01   54.01  128.66   6.33  21.05   16.81   29.06   0.97   

         SO2     O3  Benzene  Toluene  Xylene    AQI AQI_Bucket  
10229   9.25  41.68    14.36    24.86    9.84  472.0     Severe  
10230   6.65  29.97    10.55    20.09    4.29  454.0     Severe  
10231   2.65  19.71     3.91    10.23    1.99  143.0   Moderate  
10232   4.63  25.36     4.26     9.71    3.34  319.0  Very Poor  
10233   3.33  23.20     2.80     6.21    2.96  325.0  Very Poor  
...      ...    ...      ...      ...     ...    ...        ...  
12233  10.38  18.88     1.69    19.99    0.43  112.0   Moderate  
12234  10.70  18.05     1.71    25.13    1.74  196.0   Moderate  
12235  11.58  26.61     2.13    23.80    1.13  233.0       Poor  
12236  10.51  37.29     1.57    16.37    0.49  114.0   Moderate  
12237  11.15  29.73     2.03    23.57    0.65  101.0   Moderate  

[2009 rows x 16 columns]

In [119]:
df.isnull().sum()


City            0
Date            0
PM2.5           2
PM10           77
NO              2
NO2             2
NOx             0
NH3             9
CO              0
SO2           110
O3             84
Benzene         0
Toluene         0
Xylene        781
AQI            10
AQI_Bucket     10
dtype: int64

In [120]:
df= df.drop(['Xylene','Toluene','Benzene','O3','CO','SO2'], axis=1)

In [121]:
df = df.dropna()


In [122]:
df.isnull().sum()


City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
AQI           0
AQI_Bucket    0
dtype: int64

In [123]:
df

City        Date   PM2.5    PM10     NO    NO2     NOx     NH3    AQI  \
10229  Delhi  2015-01-01  313.22  607.98  69.16  36.39  110.59   33.85  472.0   
10230  Delhi  2015-01-02  186.18  269.55  62.09  32.87   88.14   31.83  454.0   
10231  Delhi  2015-01-03   87.18  131.90  25.73  30.31   47.95   69.55  143.0   
10232  Delhi  2015-01-04  151.84  241.84  25.01  36.91   48.62  130.36  319.0   
10233  Delhi  2015-01-05  146.60  219.13  14.01  34.92   38.25  122.88  325.0   
...      ...         ...     ...     ...    ...    ...     ...     ...    ...   
12233  Delhi  2020-06-27   39.80  155.94  10.88  21.46   22.47   31.43  112.0   
12234  Delhi  2020-06-28   59.52  308.65  12.67  21.60   23.86   29.27  196.0   
12235  Delhi  2020-06-29   44.86  184.12  10.50  21.57   21.94   27.97  233.0   
12236  Delhi  2020-06-30   39.80   91.98   5.99  17.96   15.44   28.48  114.0   
12237  Delhi  2020-07-01   54.01  128.66   6.33  21.05   16.81   29.06  101.0   

      AQI_Bucket  
10229     Severe  
10230     Severe  
10231   Moderate  
10232  Very Poor  
10233  Very Poor  
...          ...  
12233   Moderate  
12234   Moderate  
12235       Poor  
12236   Moderate  
12237   Moderate  

[1928 rows x 10 columns]

In [124]:
df= df.drop(['City','Date'], axis=1)

In [125]:
df

PM2.5    PM10     NO    NO2     NOx     NH3    AQI AQI_Bucket
10229  313.22  607.98  69.16  36.39  110.59   33.85  472.0     Severe
10230  186.18  269.55  62.09  32.87   88.14   31.83  454.0     Severe
10231   87.18  131.90  25.73  30.31   47.95   69.55  143.0   Moderate
10232  151.84  241.84  25.01  36.91   48.62  130.36  319.0  Very Poor
10233  146.60  219.13  14.01  34.92   38.25  122.88  325.0  Very Poor
...       ...     ...    ...    ...     ...     ...    ...        ...
12233   39.80  155.94  10.88  21.46   22.47   31.43  112.0   Moderate
12234   59.52  308.65  12.67  21.60   23.86   29.27  196.0   Moderate
12235   44.86  184.12  10.50  21.57   21.94   27.97  233.0       Poor
12236   39.80   91.98   5.99  17.96   15.44   28.48  114.0   Moderate
12237   54.01  128.66   6.33  21.05   16.81   29.06  101.0   Moderate

[1928 rows x 8 columns]

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1928 entries, 10229 to 12237
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   PM2.5       1928 non-null   float64
 1   PM10        1928 non-null   float64
 2   NO          1928 non-null   float64
 3   NO2         1928 non-null   float64
 4   NOx         1928 non-null   float64
 5   NH3         1928 non-null   float64
 6   AQI         1928 non-null   float64
 7   AQI_Bucket  1928 non-null   object 
dtypes: float64(7), object(1)
memory usage: 135.6+ KB


In [127]:
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold,train_test_split,cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [128]:
X = df[['PM2.5','PM10','NO','NO2','NOx','NH3','AQI']]
y = df['AQI_Bucket']

KeyError: ('PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'AQI')

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[125  14  13   0   0]
 [ 13 145   0   0   6]
 [  6   0  28   0   0]
 [  0   0   0  66  10]
 [  0  16   0  14 123]]
accuracy_Naive Bayes: 0.841
precision_Naive Bayes: 0.841
recall_Naive Bayes: 0.841
f1-score_Naive Bayes : 0.841


In [ ]:
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import pickle
model = GaussianNB()
model.fit(X, y)
# save the model to disk
filename = 'modelDelhi.pkl'
pickle.dump(model, open(filename, 'wb'))